catch((error) => {
    //   console.error(error); // Output: Operation failed
    // });